### ISSUE TITLE
Assumptions surrounding `is_current`

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/sequencescape-python-client#1]
Queries in `SQLAlchemyMapper` assume that all models extend `IsCurrentModel`, which they may not (according to the current implementation of the models). 

It is also assumed that an item is not of interest unless `is_current == 1`.

Are these assumptions correct?

**Comment by irinaColgiu** [comment]
Yes, the assumption that only models with the field is_current == 1 are of interest is correct.
I can't think of any scenario in which you would want something that is not current, at least not when this implies samples, studies and libraries.

**Comment by colin-nolan** [comment]
@mp15 indicated that the `is_current` field in the `current_xxx` tables is redundant and exists only due to legacy reasons.

**Comment by colin-nolan** [comment]
Use of `is_current` removed in https://github.com/wtsi-hgi/sequencescape-python-client/commit/6989107e7e833939e0b709564004f479b2472915.
