### ISSUE TITLE
connection.sample.get_by_* throws a KeyError if called with None (and not only) because it expects a non-existing key

### ISSUE THREAD

**Issue by irinaColgiu** [wtsi-hgi/sequencescape-python-client#3]
In [1]: import sequencescape

In [2]: connection = sequencescape.connect_to_sequencescape("[...]")
## In [3]: connection.sample.get_by_name(None)

KeyError                                  Traceback (most recent call last)
<ipython-input-3-ee3b28296e0d> in <module>()
----> 1 connection.sample.get_by_name(None)

/nfs/users/nfs_i/ic4/Projects/python3/meta-check/ENV/lib/python3.5/site-packages/sequencescape/mappers.py in get_by_name(self, names)
     89         :return: sequence of models of data with the given names(s)
     90         """
---> 91         results = self.get_by_property_value(Property.NAME, names)
     92         assert isinstance(results, collections.Sequence)
     93         return results

/nfs/users/nfs_i/ic4/Projects/python3/meta-check/ENV/lib/python3.5/site-packages/sequencescape/mappers.py in get_by_property_value(self, property, values)
     54             if isinstance(values, str) or isinstance(values, int):
     55                 values = [values]
---> 56             return self._get_by_property_value_sequence(property, values)
     57         else:
     58             return self._get_by_property_value_tuple(property)

/nfs/users/nfs_i/ic4/Projects/python3/meta-check/ENV/lib/python3.5/site-packages/sequencescape/_sqlalchemy/sqlalchemy_mappers.py in _get_by_property_value_sequence(self, property, required_property_values)
     68 
     69         # FIXME: It is an assumption that the Model property has the same build_name as SQLAlchemyModel property
---> 70         query_column = query_model.__dict__[property]   # type: Column
     71         results = session.query(query_model). \
     72             filter(query_column.in_(required_property_values)).\

KeyError: 'build_name'

**Comment by colin-nolan** [comment]
The `name` parameter on `get_by_name` is not optional:
https://github.com/wtsi-hgi/python-sequencescape-client/blob/master/sequencescape/mappers.py#L85
Given that the input is unexpected (i.e. it is not a permitted "type"), it is not suprising that an error is raised.

Although a `ValueError` would be more appropriate in this case, this would require input checks. As Python is dynamically typed, always checking that inputs are of the expected type would be a pain and is rarely done in Python libraries.

**Comment by irinaColgiu** [comment]
Yes, but for me as a client it is non-intuitive to get a random "KeyError  "build_name" doesn't exist", which I have no idea what it means and doesn't give any insight over what I did wrong. While I agree that you shouldn't always check on the parameter type, I think it's a good idea to check on the arguments you get from your external client, even if you agree on a high level of trust between the methods within your library. Otherwise in a different context you might end up inserting in a database 100 rows containing only None for example, just because you haven't checked what the data has the client sent you.

BTW, I was wrong, I am not getting the error because I call get_by_name with None, but when I call it with a valid list of ids:

## In [8]: connection.sample.get_by_name(['SC_BLUE5620006'])

KeyError                                  Traceback (most recent call last)
<ipython-input-8-d956743296fa> in <module>()
----> 1 connection.sample.get_by_name(['SC_BLUE5620006'])

/nfs/users/nfs_i/ic4/Projects/python3/meta-check/ENV/lib/python3.5/site-packages/sequencescape/mappers.py in get_by_name(self, names)
     89         :return: sequence of models of data with the given names(s)
     90         """
---> 91         results = self.get_by_property_value(Property.NAME, names)
     92         assert isinstance(results, collections.Sequence)
     93         return results

/nfs/users/nfs_i/ic4/Projects/python3/meta-check/ENV/lib/python3.5/site-packages/sequencescape/mappers.py in get_by_property_value(self, property, values)
     54             if isinstance(values, str) or isinstance(values, int):
     55                 values = [values]
---> 56             return self._get_by_property_value_sequence(property, values)
     57         else:
     58             return self._get_by_property_value_tuple(property)

/nfs/users/nfs_i/ic4/Projects/python3/meta-check/ENV/lib/python3.5/site-packages/sequencescape/_sqlalchemy/sqlalchemy_mappers.py in _get_by_property_value_sequence(self, property, required_property_values)
     68 
     69         # FIXME: It is an assumption that the Model property has the same build_name as SQLAlchemyModel property
---> 70         query_column = query_model.__dict__[property]   # type: Column
     71         results = session.query(query_model). \
     72             filter(query_column.in_(required_property_values)).\

KeyError: 'build_name'

**Comment by colin-nolan** [comment]
WRT type checking: I don't like it as much as you but Python is generally written with a GIGO view of the world, which indeed leads to strange error messages when inputs are wrong.

As for the issue you've discovered when using valid input - I have found the root of the problem:
https://github.com/wtsi-hgi/python-sequencescape-client/commit/2dea086e5c1361e91ef9ac82269bc472ffc4f12e#diff-b5cf137108f3eca1b51545295067e6b0L5
This change was made when I automatically refactored a string, something which PyCharm is not great at (I have since stopped doing it).

This problem highlights the need to solve https://github.com/wtsi-hgi/python-sequencescape-client/issues/2 as such testing would have detected the problem.

I shall fix this now...

**Comment by irinaColgiu** [comment]
There is no GIGO view of the world in this case, it's just the client passing the wrong types of parameters it is a question of developer choice whether to check or not on the input.  So if anything, in this case it is garbage in, nothing-out-cause-it-threw-a-random-exception.
GIGO is usually used for input data of poor quality, while in this case there is no discussion about the quality of your input data, but about giving it the right type, so the discussion is the zone of "what do I do when I get apples instead of pears?"
