### ISSUE TITLE
 connection.sample.get_associated_with_study([])  raises IndexError: list index out of range

### ISSUE THREAD

**Issue by irinaColgiu** [wtsi-hgi/sequencescape-python-client#4]
OK, this one I think shouldn't raise an exception when called with an empty list:

In [5]: connection.sample.get_associated_with_study([])

IndexError                                Traceback (most recent call last)
<ipython-input-5-3d9d8eda2ac3> in <module>()
----> 1 connection.sample.get_associated_with_study([])

/nfs/users/nfs_i/ic4/Projects/python3/meta-check/ENV/lib/python3.5/site-packages/sequencescape/_sqlalchemy/sqlalchemy_mappers.py in get_associated_with_study(self, studies)
    181 
    182     def get_associated_with_study(self, studies: Union[Study, Iterable[Study]]) -> Sequence[Sample]:
--> 183         return self._get_association(studies, "samples")
    184 
    185 

/nfs/users/nfs_i/ic4/Projects/python3/meta-check/ENV/lib/python3.5/site-packages/sequencescape/_sqlalchemy/sqlalchemy_mappers.py in _get_association(self, associated_with, relationship_property_name)
    138 
    139         session = self._database_connector.create_session()
--> 140         sqlalchemy_associated_with_type = get_equivalent_sqlalchemy_model_type(associated_with[0].__class__)
    141         assert sqlalchemy_associated_with_type != None
    142         results = session.query(sqlalchemy_associated_with_type). \

IndexError: list index out of range

**Comment by colin-nolan** [comment]
This is a bug in the library code:
`sqlalchemy_associated_with_type = get_equivalent_sqlalchemy_model_type(associated_with[0].__class__)`

I shall fix and add regression tests now.
